### ISSUE TITLE
Programmatically create QnA Maker knowledge bases for each factsheet

### ISSUE THREAD

**Issue by nicholasamiller** [govlawtech/dvachatbot#2]
Ching, 

Here is a present for you - all the factsheets stripped of surrounding text, nice and clean ready for QnA maker to scrape.
First thing I would try is to create a knowledge base for each of these programatically using the QnA api:
https://westus.dev.cognitive.microsoft.com/docs/services/58994a073d9e04097c7ba6fe/operations/58994a073d9e041ad42d9baa

There might be something in the factsheets that makes them not amenable to scraping, or something we could do to make them more amendable.  In that case, I would recommend massaging the source, regenerating HTML factsheets to scrape, and rescraping using the QnA API - rather than amending via the QnA UI.  The former approach will hopefully scale better.  

The code to spit out the cleaned up fact sheet html is in https://github.com/govlawtech/dvawebsitescraper in the 'FactSheetAnalyzer' project.

Factsheet urls to scrape:

https://dvachatbotstorage.blob.core.windows.net/factsheets/BR04.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/CEP01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CEP03.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CON01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CON02.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CON03.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CON04.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CON05.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CON06.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CON07.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/CON08.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP01.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP02.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP13.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP15.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP18.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP22.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP23.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP28.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP29.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP30.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP42.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP43.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP50.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP60.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP68.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP71.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP72.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP73.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP74.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP75.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP76.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP78.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP79.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP81.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP82.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP83.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP84.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DP85.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/DVA03.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/DVA06.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/DVA19.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/DVA21.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/DVA23.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/F111.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/FIP01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/FIP02.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/FIP04.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/GS01.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/GS02.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/GS03.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/GS04.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/GS05.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/HAC01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HAC02.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HCS01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HCS05.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HCS10.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HIP01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HIP06.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HIP40.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HIP72.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HIP80.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HIP90.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV02.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV03.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV05.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV06.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV10.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV100.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV101.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV107.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV108.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV109.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV120.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV13.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV131.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV132.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV136.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV137.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV139.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV14.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV140.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV16.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV17.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV18.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV19.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV20.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV21.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV22.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV23.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV27.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV29.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV30.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV59.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV60.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV61.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV62.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV64.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV65.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV69.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV74.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV77.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV80.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV92.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV93.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV97.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/HSV99.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IP01.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS01.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS02.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS03.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS04.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS05.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS06.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS07.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS08.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS09.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS10.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS101.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS103.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS104.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS105.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS106.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS115.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS116.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS117.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS12.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS121.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS122.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS125.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS126.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS135.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS137.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS138.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS139.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS140.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS141.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS142.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS143.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS144.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS145.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS147.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS15.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS150.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS151.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS154.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS155.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS156.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS158.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS159.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS16.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS160.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS161.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS163.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS164.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS165.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS166.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS167.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS168.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS18.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS184.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS185.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS186.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS187.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS188.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS19.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS29.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS30.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS34.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS35.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS44.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS45.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS46.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS47.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS48.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS50.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS57.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS58.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS65.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS71.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS72.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS73.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS74.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS75.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS77.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS79.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS81.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS82.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS85.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS86.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS87.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS88.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS89.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS90.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS91.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS92.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS94.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS95.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS96.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS97.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS98.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/IS99.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/LEG01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/LEG02.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MCS01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MCS07.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MCS13.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC04.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC05.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC07.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC08.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC09.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC10.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC17.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC18.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC25.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC27.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC30.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC31.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC33.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC34.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC35.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC36.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC39.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC40.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC41.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC42.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC43.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC45.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC47.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC49.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/MRC50.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/NR01.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/POW01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/POW02.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/VCS01.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/VCS02.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/VCS03.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/VRB01.htm 
https://dvachatbotstorage.blob.core.windows.net/factsheets/VRB02.html
https://dvachatbotstorage.blob.core.windows.net/factsheets/VRB03.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/VRB04.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/VRB05.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/VRB06.html 
https://dvachatbotstorage.blob.core.windows.net/factsheets/WG01.html  
https://dvachatbotstorage.blob.core.windows.net/factsheets/WG02.html

**Comment by cchew** [comment]
Completed for MRCA
